name: Check for www links
run: |
  if grep -rnw 'www\.toxiguard' ./src; then
    echo "❌ Found forbidden www links!"
    exit 1
  fi

name: Check for removed pages
run: |
  forbidden_paths=("how-it-works" "waitlist" "blog")
  for path in "${forbidden_paths[@]}"; do
    if [ -d "src/app/${path}" ]; then
      echo "❌ Found forbidden directory: src/app/${path}"
      exit 1
    fi
  done

name: SEO Health Check
run: |
  npm install -g seo-checker
  seo-check https://toxiguard.site --rules=canonical,meta-tags,structured-data

name: Build Check
run: |
  npm run build || (
    echo "Build failed. Common issues:"
    echo "1. Check for missing dependencies"
    echo "2. Verify all imports exist"
    echo "3. Check for undefined variables"
    exit 1
  ) 